//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewableVoting.IO.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.UnconfirmedVotes = new HashSet<UnconfirmedVote>();
            this.Votes = new HashSet<Vote>();
        }
    
        public int CandidateID { get; set; }
        public Nullable<int> VoterID { get; set; }
        public Nullable<int> ElectionID { get; set; }
        public Nullable<int> PartyID { get; set; }
        public long CandidateChecksum { get; set; }
    
        public virtual Election Election { get; set; }
        public virtual Party Party { get; set; }
        public virtual Voter Voter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnconfirmedVote> UnconfirmedVotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vote> Votes { get; set; }
    }
}
