//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewableVoting.IO.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public int VoteID { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<int> CandidateID { get; set; }
        public Nullable<int> voterID { get; set; }
        public string VoteCheckSum { get; set; }
        public string CheckSum { get; set; }
        public string CumulativeCheckSum { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual Voter Voter { get; set; }
    }
}
