//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewableVoting.IO.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoterAddress
    {
        public int VoterAddressID { get; set; }
        public int VoterID { get; set; }
        public Nullable<int> StreetAddressID { get; set; }
    
        public virtual StreetAddress StreetAddress { get; set; }
        public virtual Voter Voter { get; set; }
    }
}
